version: "3.9"
services:
  pdns:
    build:
      context: pdns
      args:
        PDNS_BACKEND_PACKAGES: pdns-backend-pgsql postgresql-client
        PDNSCONF_LAUNCH: gpgsql
    #image: interlegis/powerdns:4.9.0
    links:
      - "postgres:postgres"
    ports:
      - "53"
      - "53/udp"
      - "8088:8081"
    environment:
      - PDNSCONF_API_KEY=a_strong_api_key
      - PDNSCONF_DNSUPDATE=yes
      - SECALLZONES_CRONJOB=yes
      - PDNSCONF_GPGSQL_HOST=postgres
      - PDNSCONF_GPGSQL_USER=pdns
      - PDNSCONF_GPGSQL_DBNAME=pdns
      - PDNSCONF_GPGSQL_PASSWORD=pdnspw
    stop_signal: TERM

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: pdnspw
      POSTGRES_USER: pdns
      POSTGRES_DB: pdns
    volumes:
      - dnsmasterdb:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  dnsmasterdb:
    driver: local
