name: pgsql Docker image build

on:
  push:
    branches:
      - 'master'
      - 'ci'
      - '[0-9]+'
      - '[0-9]+.[0-9]+'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    with:
      suffix: -pgsql
      is_default_flavor: false
      build_args: |
        PDNS_BACKEND_PACKAGES=pdns-backend-pgsql postgresql-client
        PDNSCONF_LAUNCH=gpgsql
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
